name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install deps
        run: npm i
      # Build app for production
      - name: Build app bundle
        run: npm run build
      # Deploy to GitHub Pages
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: production
          build_dir: dist/angular-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}